/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AmenityService } from "../amenity.service";
import { AmenityCreateInput } from "./AmenityCreateInput";
import { Amenity } from "./Amenity";
import { AmenityFindManyArgs } from "./AmenityFindManyArgs";
import { AmenityWhereUniqueInput } from "./AmenityWhereUniqueInput";
import { AmenityUpdateInput } from "./AmenityUpdateInput";
import { BookingFindManyArgs } from "../../booking/base/BookingFindManyArgs";
import { Booking } from "../../booking/base/Booking";
import { BookingWhereUniqueInput } from "../../booking/base/BookingWhereUniqueInput";

export class AmenityControllerBase {
  constructor(protected readonly service: AmenityService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Amenity })
  async createAmenity(
    @common.Body() data: AmenityCreateInput
  ): Promise<Amenity> {
    return await this.service.createAmenity({
      data: {
        ...data,

        villa: data.villa
          ? {
              connect: data.villa,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        description: true,
        id: true,
        images: true,
        name: true,
        typeField: true,
        updatedAt: true,

        villa: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Amenity] })
  @ApiNestedQuery(AmenityFindManyArgs)
  async amenities(@common.Req() request: Request): Promise<Amenity[]> {
    const args = plainToClass(AmenityFindManyArgs, request.query);
    return this.service.amenities({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        images: true,
        name: true,
        typeField: true,
        updatedAt: true,

        villa: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Amenity })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async amenity(
    @common.Param() params: AmenityWhereUniqueInput
  ): Promise<Amenity | null> {
    const result = await this.service.amenity({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        images: true,
        name: true,
        typeField: true,
        updatedAt: true,

        villa: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Amenity })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateAmenity(
    @common.Param() params: AmenityWhereUniqueInput,
    @common.Body() data: AmenityUpdateInput
  ): Promise<Amenity | null> {
    try {
      return await this.service.updateAmenity({
        where: params,
        data: {
          ...data,

          villa: data.villa
            ? {
                connect: data.villa,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          description: true,
          id: true,
          images: true,
          name: true,
          typeField: true,
          updatedAt: true,

          villa: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Amenity })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteAmenity(
    @common.Param() params: AmenityWhereUniqueInput
  ): Promise<Amenity | null> {
    try {
      return await this.service.deleteAmenity({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          images: true,
          name: true,
          typeField: true,
          updatedAt: true,

          villa: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/bookings")
  @ApiNestedQuery(BookingFindManyArgs)
  async findBookings(
    @common.Req() request: Request,
    @common.Param() params: AmenityWhereUniqueInput
  ): Promise<Booking[]> {
    const query = plainToClass(BookingFindManyArgs, request.query);
    const results = await this.service.findBookings(params.id, {
      ...query,
      select: {
        amenity: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        dateFrom: true,
        dateTo: true,
        id: true,

        servicePackage: {
          select: {
            id: true,
          },
        },

        status: true,
        totalPrice: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        villa: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/bookings")
  async connectBookings(
    @common.Param() params: AmenityWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        connect: body,
      },
    };
    await this.service.updateAmenity({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/bookings")
  async updateBookings(
    @common.Param() params: AmenityWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        set: body,
      },
    };
    await this.service.updateAmenity({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/bookings")
  async disconnectBookings(
    @common.Param() params: AmenityWhereUniqueInput,
    @common.Body() body: BookingWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      bookings: {
        disconnect: body,
      },
    };
    await this.service.updateAmenity({
      where: params,
      data,
      select: { id: true },
    });
  }
}
