/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AmenityWhereUniqueInput } from "../../amenity/base/AmenityWhereUniqueInput";

import {
  ValidateNested,
  IsOptional,
  IsDate,
  IsString,
  MaxLength,
  IsNumber,
  Min,
  Max,
} from "class-validator";

import { Type } from "class-transformer";
import { ServicePackageWhereUniqueInput } from "../../servicePackage/base/ServicePackageWhereUniqueInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";
import { VillaWhereUniqueInput } from "../../villa/base/VillaWhereUniqueInput";

@InputType()
class BookingUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AmenityWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AmenityWhereUniqueInput)
  @IsOptional()
  @Field(() => AmenityWhereUniqueInput, {
    nullable: true,
  })
  amenity?: AmenityWhereUniqueInput | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  dateFrom?: Date | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  dateTo?: Date | null;

  @ApiProperty({
    required: false,
    type: () => ServicePackageWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ServicePackageWhereUniqueInput)
  @IsOptional()
  @Field(() => ServicePackageWhereUniqueInput, {
    nullable: true,
  })
  servicePackage?: ServicePackageWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  status?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  totalPrice?: number | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => VillaWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => VillaWhereUniqueInput)
  @IsOptional()
  @Field(() => VillaWhereUniqueInput, {
    nullable: true,
  })
  villa?: VillaWhereUniqueInput | null;
}

export { BookingUpdateInput as BookingUpdateInput };
