/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsInt,
  Min,
  Max,
  ValidateNested,
} from "class-validator";
import { BookingCreateNestedManyWithoutVillasInput } from "./BookingCreateNestedManyWithoutVillasInput";
import { Type } from "class-transformer";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { ServiceCreateNestedManyWithoutVillasInput } from "./ServiceCreateNestedManyWithoutVillasInput";

@InputType()
class VillaCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  address?: string | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  areaSqrm?: number | null;

  @ApiProperty({
    required: false,
    type: () => BookingCreateNestedManyWithoutVillasInput,
  })
  @ValidateNested()
  @Type(() => BookingCreateNestedManyWithoutVillasInput)
  @IsOptional()
  @Field(() => BookingCreateNestedManyWithoutVillasInput, {
    nullable: true,
  })
  bookings?: BookingCreateNestedManyWithoutVillasInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  images?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => ServiceCreateNestedManyWithoutVillasInput,
  })
  @ValidateNested()
  @Type(() => ServiceCreateNestedManyWithoutVillasInput)
  @IsOptional()
  @Field(() => ServiceCreateNestedManyWithoutVillasInput, {
    nullable: true,
  })
  services?: ServiceCreateNestedManyWithoutVillasInput;
}

export { VillaCreateInput as VillaCreateInput };
