/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { LanguageContent } from "./LanguageContent";
import { LanguageContentCountArgs } from "./LanguageContentCountArgs";
import { LanguageContentFindManyArgs } from "./LanguageContentFindManyArgs";
import { LanguageContentFindUniqueArgs } from "./LanguageContentFindUniqueArgs";
import { CreateLanguageContentArgs } from "./CreateLanguageContentArgs";
import { UpdateLanguageContentArgs } from "./UpdateLanguageContentArgs";
import { DeleteLanguageContentArgs } from "./DeleteLanguageContentArgs";
import { LanguageContentService } from "../languageContent.service";
@graphql.Resolver(() => LanguageContent)
export class LanguageContentResolverBase {
  constructor(protected readonly service: LanguageContentService) {}

  async _languageContentsMeta(
    @graphql.Args() args: LanguageContentCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [LanguageContent])
  async languageContents(
    @graphql.Args() args: LanguageContentFindManyArgs
  ): Promise<LanguageContent[]> {
    return this.service.languageContents(args);
  }

  @graphql.Query(() => LanguageContent, { nullable: true })
  async languageContent(
    @graphql.Args() args: LanguageContentFindUniqueArgs
  ): Promise<LanguageContent | null> {
    const result = await this.service.languageContent(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => LanguageContent)
  async createLanguageContent(
    @graphql.Args() args: CreateLanguageContentArgs
  ): Promise<LanguageContent> {
    return await this.service.createLanguageContent({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => LanguageContent)
  async updateLanguageContent(
    @graphql.Args() args: UpdateLanguageContentArgs
  ): Promise<LanguageContent | null> {
    try {
      return await this.service.updateLanguageContent({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => LanguageContent)
  async deleteLanguageContent(
    @graphql.Args() args: DeleteLanguageContentArgs
  ): Promise<LanguageContent | null> {
    try {
      return await this.service.deleteLanguageContent(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
